# No Title

[Original Post](https://discourse.onlinedegree.iitm.ac.in/t/171141/349)

<p><a class="mention" href="/u/carlton">@carlton</a> and <a class="mention" href="/u/jivraj">@Jivraj</a> , for Task A i had tested before and all the test cases passed, but all my A tasks has failed with 0, In the evaluation logs, i could see that all task A tests failed due to datagen.py not available.</p>
<p>Could you rerun the test ?</p>